### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by twjeric** [yi-ji/NeteaseMusicAbroad#10]
MacOS 10.11.6
NeteaseMusic 1.5.9 (622)
Python 2.7.13

- [x] Open NeteaseMusicHelper before launching Netease Music App
- [x] Automatic Proxy Configuration is set
- [x] Make sure the helper is running by checking its pid
- [x] service_identity library installed
- [ ] Still showing grey and "... your region is block"

**Comment by twjeric** [comment]
$ python NeteaseMusicProxy.py
2018-09-17 15:09:21-0700 [-] Log opened.
2018-09-17 15:09:22-0700 [-] NeteaseMusicProxyFactory starting on 32794
2018-09-17 15:09:22-0700 [-] Starting factory <__main__.NeteaseMusicProxyFactory instance at 0x111c795f0>

**Comment by yi-ji** [comment]
Please try to uninstall and reinstall your NeteaseMusic, then restart helper

**Comment by yi-ji** [comment]
Btw which network interface are you using? Wi-if or Ethernet?

**Comment by yi-ji** [comment]
Also please check the PAC file path if you had moved or renamed the repo folder.

**Comment by yi-ji** [comment]
if no response or any follow-up, this issue is closed.
