### ISSUE TITLE
不知道什么情况……

### ISSUE THREAD

**Issue by YichaoLeoLi** [yi-ji/NeteaseMusicAbroad#12]
<img width="588" alt="screen shot 2018-10-18 at 12 03 31 am" src="https://user-images.githubusercontent.com/43074923/47130999-5d63fb80-d26a-11e8-960a-069f8736384c.png">
我把所有的东西都装了之后运行NetEaseMusicHelper就变成这样了……

**Comment by yi-ji** [comment]
如无回复则close该issue
