### ISSUE TITLE
正常运行以后显示operation not permitted

### ISSUE THREAD

**Issue by allenshi1011** [yi-ji/NeteaseMusicAbroad#13]
![image](https://user-images.githubusercontent.com/43126589/47400054-74826d80-d6f0-11e8-804e-5781d34a6e40.png)
运行过后还是不行呀
![image](https://user-images.githubusercontent.com/43126589/47400077-8cf28800-d6f0-11e8-9e89-7e9225e3de20.png)

**Comment by yi-ji** [comment]
首先那些Operation permitted毫无影响，不用管；

检查是否安装了Twisted, requests和PyQuery？
请尝试重启网易云音乐并刷新歌单，如仍无效，执行`python NeteaseMusicProxy.py`并把输出贴到这里

**Comment by allenshi1011** [comment]
都安装过了呀，我对python不是很了解只是对这个程序比较感兴趣所以比较小白见谅，

yi-ji <notifications@github.com> 于2018年10月23日周二 下午7:41写道：

**Comment by allenshi1011** [comment]
重新安装后打开那个helper变成这样了，然后proxy的截图

yi-ji <notifications@github.com> 于2018年10月26日周五 上午1:27写道：

**Comment by yi-ji** [comment]
链接打不开
直接把图放进评论来？

**Comment by allenshi1011** [comment]
<img width="652" alt="wechat7af6bf4e7593f9f676f0711518f8d23e" src="https://user-images.githubusercontent.com/43126589/47599392-0fce4980-d962-11e8-8e2a-9363e7d941ff.png">
<img width="585" alt="wechatb5ce64b3c305e9c65213c8ec456bc6d2" src="https://user-images.githubusercontent.com/43126589/47599393-0fce4980-d962-11e8-8432-bc961f29ee25.png">

**Comment by yi-ji** [comment]
已修改，请重新下载使用NeteaseMusicAbroad :)

**Comment by yi-ji** [comment]
若无回复则close该issue。
