### ISSUE TITLE
exe正常执行之后仍然显示“因合作无法播放“

### ISSUE THREAD

**Issue by yaoyua** [yi-ji/NeteaseMusicAbroad#14]
1. 运行 ./NeteaseMusicHelper
<img width="572" alt="screen shot 2018-10-27 at 5 49 14 pm" src="https://user-images.githubusercontent.com/22032281/47609650-c852c680-da10-11e8-9f96-a5000bced1ea.png">
2. 打开mac网易云显示灰色，无法播放
3. 运行 python NeteaseMusicProxy.py
<img width="567" alt="screen shot 2018-10-27 at 5 51 40 pm" src="https://user-images.githubusercontent.com/22032281/47609661-fb955580-da10-11e8-85e7-fb09fbf74c46.png">
望能够尽快答复，非常感谢

**Comment by yaoyua** [comment]
我用的客户端是1.5.9；python是anaconda 3，Twisted, pyquery, requests, pyOpenSSL均已经安装。

**Comment by yi-ji** [comment]
python的输出只有那一点的话，说明proxy没收到任何request，所以请检查：
打开 System Preference （系统偏好设置） -> Network （网络） -> Advanced （高级） -> Proxies （代理） -> Automatic Proxy Configuration 截图看一下？

**Comment by ajaxsys** [comment]
@yaoyua 

> 运行 python NeteaseMusicProxy.py

等过一会会有更多log出现。然后就可以了。。。如果不行

      ps -ef | grep Netease

然后把里面但相关进程kill掉试一下。

**Comment by yi-ji** [comment]
谢楼上。如无后续回复则close该issue。
