### ISSUE TITLE
Mac OS运行提示需要访问照片、通讯录等

### ISSUE THREAD

**Issue by mikumeow** [yi-ji/NeteaseMusicAbroad#15]
我在Mac OS端以普通用户身份打开NeteaseMusicHelper，显示了一堆需要访问照片、通讯录等内容的请求，控制台输出如下：
find: /Users/schin//Pictures/Photos Library.photoslibrary: Operation not permitted
find: /Users/schin//Library/Application Support/MobileSync: Operation not permitted
find: /Users/schin//Library/Application Support/CallHistoryTransactions: Operation not permitted
find: /Users/schin//Library/Application Support/com.apple.TCC: Operation not permitted
find: /Users/schin//Library/Application Support/AddressBook: Operation not permitted
find: /Users/schin//Library/Application Support/CallHistoryDB: Operation not permitted
find: /Users/schin//Library/IdentityServices: Operation not permitted
find: /Users/schin//Library/Calendars: Operation not permitted
find: /Users/schin//Library/Messages: Operation not permitted
find: /Users/schin//Library/HomeKit: Operation not permitted
find: /Users/schin//Library/Python: Permission denied
find: /Users/schin//Library/Mail: Operation not permitted
find: /Users/schin//Library/Safari: Operation not permitted
find: /Users/schin//Library/Suggestions: Operation not permitted
find: /Users/schin//Library/Containers/com.apple.VoiceMemos: Operation not permitted
find: /Users/schin//Library/Containers/com.apple.Home: Operation not permitted
find: /Users/schin//Library/Containers/com.apple.Safari: Operation not permitted
find: /Users/schin//Library/Containers/com.apple.iChat: Operation not permitted
find: /Users/schin//Library/Containers/com.apple.mail: Operation not permitted
find: /Users/schin//Library/Containers/com.apple.news: Operation not permitted
find: /Users/schin//Library/Containers/com.apple.stocks: Operation not permitted
find: /Users/schin//Library/PersonalizationPortrait: Operation not permitted
find: /Users/schin//Library/Metadata/CoreSpotlight: Operation not permitted
find: /Users/schin//Library/Metadata/com.apple.IntelligentSuggestions: Operation not permitted
find: /Users/schin//Library/Cookies: Operation not permitted
find: /Users/schin//Library/Caches/com.apple.safaridavclient: Operation not permitted
find: /Users/schin//Library/Caches/CloudKit/com.apple.Safari: Operation not permitted
find: /Users/schin//Library/Caches/com.apple.Safari: Operation not permitted
find: /Users/schin//Library/Caches/com.apple.Safari.SafeBrowsing: Operation not permitted
请问这是正常情况吗？

**Comment by yi-ji** [comment]
我来解释一下，这一堆Operation not permitted是find命令在~/目录下寻找NeteaseMusicHelper时提示的，因为~/目录下面有些地方以普通用户身份连读权限也没有（root创建的）。
当然，这个做法很蠢，现在已经改掉了，不再用find命令。请下载并使用最新的NeteaseMusicHelper
