### ISSUE TITLE
pip无效

### ISSUE THREAD

**Issue by INPUTrrr0** [yi-ji/NeteaseMusicAbroad#17]
terminal显示-bash: pip: command not found？
请问这是为什么。。。

pip install twisted requests pyquery --user ， user这里改了或者删掉也不可以。
然后sudo 也不可以。。。

谢谢！

**Comment by yi-ji** [comment]
执行`sudo easy_install pip`来安装pip

**Comment by INPUTrrr0** [comment]
啊啊！好了qaq 谢谢！
