### ISSUE TITLE
[网易云音乐版本升级] macOS NeteaseMusic Version >= 1.5.10 失效 

### ISSUE THREAD

**Issue by XinyuLyu** [yi-ji/NeteaseMusicAbroad#20]
网易云音乐升级到最新版本之后，不能用了。

**Comment by yi-ji** [comment]
感谢报告，问题已确认，正在尝试解决。同时希望能提供更详细的问题描述🙏
在解决之前请用回旧版本吧

**Comment by yi-ji** [comment]
初步怀疑是cn-proxy.com被网易服务器refused，暂时切换到了缺省的阿里云代理，可以正常听歌了。请重新下载最新的NeteaseMusicAbroad使用！

**Comment by XinyuLyu** [comment]
好的 谢谢！

**Comment by yi-ji** [comment]
@XinyuLyu 如后续无问题则close该issue。还有问题的话可以reopen

**Comment by ty323** [comment]
不知道原问题的“失效”是什么意思 我今天clone之后按readme试了下 打开网易云音乐之后无法连接到网络 请问是同一个问题吗？该如何解决？
