### ISSUE TITLE
NeteaseMusicHelper 中修改python版本

### ISSUE THREAD

**Issue by llafcode** [yi-ji/NeteaseMusicAbroad#23]
环境：
OS：MAC OS 10.14.1
Python: Anaconda python 3.7
网络：学校WiFi

代码下载顺利，依赖库使用的conda install XXX （我的pip版本仍旧停留在2.7），安装成功。

我的pip和python版本一致，看到README中提到此种情况需要修改NeteaseMusicHelper文件中python版本，但是使用编辑器打开NeteaseMusicHelper不知应该修改哪里。。

``if [ "`uname`" = "Darwin" ]``
``then``
``    cd `dirname $0``
``fi``
``rm -f nohup.out helper.log``
``touch helper.log``
``nohup /bin/bash run_`uname`.sh > /dev/null &``
``tail -f helper.log``

请指教。

另：
尝试运行python NeteaseMusicProxy.py 但保持如下输出几分钟没有变化属于正常情况吗？

`2018-11-26 16:22:18+0200 [-] Log opened.`
`2018-11-26 16:22:19+0200 [-] NeteaseMusicProxyFactory starting on 32794`
`2018-11-26 16:22:19+0200 [-] Starting factory <__main__.NeteaseMusicProxyFactory object at 0x112ac36d8>`

**Comment by yi-ji** [comment]
pip 2.7没关系，只要你用conda install的package是python 3的package就行。所以不需要修改。
readme是我写错了，如果需要修改，应该是run_*.sh，谢谢提示。

你的输出说明依赖的packages都没问题，没后续输出是不是没启动网易云音乐？启动了的话请按照FAQ查看网络设置

**Comment by llafcode** [comment]
谢谢回答，的确是因为没打开网易云。。因为之前没效果，我以为是pip和python版本不一致的问题，没找到怎么修改NeteaseMusicHelper文件就没再打开网易云音乐。

现在尝试了一下之前歌单里灰色的歌名都变黑了，随机试了几首可以听，十分感谢～

如果使用过程中再有问题会再来请教。
