### ISSUE TITLE
求问mac自动代理配置文件的路径怎么设置？

### ISSUE THREAD

**Issue by SkyOL5** [yi-ji/NeteaseMusicAbroad#26]

**Comment by SkyOL5** [comment]
如题，我不知道是不是自动代理路径的问题。

**Comment by SkyOL5** [comment]
我是python 3.7版本，三个包都安装了，运行helper能够启动网易云音乐，但是依旧会有很多受到权限的歌曲

**Comment by yi-ji** [comment]
你的意思是说，你运行helper之后，打开自动代理设置，配置文件的路径是空的？
请看#25来手动设置。

如果愿意帮忙定位bug，请在手动设置配置文件之前执行一下`/bin/bash -x run_Darwin.sh`并贴下输出，谢谢！

**Comment by SkyOL5** [comment]
1. 自动代理配置点勾，没有输入pac本地文件地址
运行文件NeteaseMusicProxy.py输入如下：
![1545276802905](https://user-images.githubusercontent.com/45924398/50262269-558c2780-0464-11e9-9e36-a43964e9eb36.jpg)
【anaconda 配置的 python 3.7】
运行helper后，网易云音乐正常启动，歌曲灰色，然后自动代理配置的文件路径为空
bash下运行run_Darwin.sh文件，输出：
appending output to nohup.out

**Comment by SkyOL5** [comment]
2. 自动代理配置打勾，pac文件路径正确输入
此时music.163.com无法正常打开，同时，所有其他网址都无法打开【断网状态】
运行helper可以正常打开网易云音乐，所有界面均显示正在加载中【断网状态】
运行同环境下的NeteaseMusicProxy.py，输出如下：
<img width="1224" alt="output" src="https://user-images.githubusercontent.com/45924398/50262408-52de0200-0465-11e9-8034-df269b9392aa.png">
目前不清楚具体哪一步出现了问题，求教

**Comment by SkyOL5** [comment]
oh，对了，我是在校园Wi-Fi的环境下输入的代理文件地址，不知道是不是相关

**Comment by SkyOL5** [comment]
我的微信是zy13707nottingham，方便的话可以加个微信嘛

**Comment by SkyOL5** [comment]
file:///Users/skyol/Downloads/NeteaseMusicAbroad-master/NeteaseMusic.pac
对的，这个是我配置文件的路径

**Comment by SkyOL5** [comment]
执行run_Darwin.sh的结果：【自动代理配置没勾选，配置文件路径为空的情况】

Last login: Thu Dec 20 14:56:30 on ttys000
vlan-2661-10-19-244-218:~ skyol$ /bin/bash -x /Users/skyol/Downloads/NeteaseMusicAbroad-master/run_Linux.sh 
+ print_log 'The change been made can be recovered by bash: gsettings set org.gnome.system.proxy mode none'
+ echo ''
+ echo The change been made can be recovered by bash: gsettings set org.gnome.system.proxy mode none
+ gsettings set org.gnome.system.proxy mode auto
No schemas installed
++ pwd
+ gsettings set org.gnome.system.proxy autoconfig-url file:///Users/skyol/NeteaseMusic.pac
No schemas installed
+ print_log 'All set, you can launch your NeteaseMusic App and close me now.'
+ echo ''
+ nohup python NeteaseMusicProxy.py
+ echo All set, you can launch your NeteaseMusic App and close me now.
+ print_log 'Don'\''t worry about me, I will terminate myself a few seconds after you quit NeteaseMusic.'
+ echo ''
+ echo 'Don'\''t' worry about me, I will terminate myself a few seconds after you quit NeteaseMusic.
++ ps x
++ grep NeteaseMusicProxy
++ awk '{print $1;}'
++ head -1
+ pid=13093
+ true
+ sleep 60
++ ps x
++ grep netease-cloud-music
++ wc -l
++ xargs
+ '[' 1 -eq 1 ']'
+ kill -9 13093
/Users/skyol/Downloads/NeteaseMusicAbroad-master/run_Linux.sh: line 24: kill: (13093) - No such process
+ break

**Comment by SkyOL5** [comment]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/45924398/50266953-be31cf00-0479-11e9-80c3-ba3ea2a9c9c7.png">
自动代理配置开启，配置文件路径正确的情况下，python卡在了这里，一直没有终止，但等了小半个小时，也没有其他输出了

**Comment by yi-ji** [comment]
谢谢！不过你执行的是run_Linux.sh
麻烦执行下面：(还是先取消并清空自动代理设置)
`cd /Users/skyol/Downloads/NeteaseMusicAbroad-master`
`/bin/bash -x run_Darwin.sh` 

那个不是卡住了，而是在等待请求，没有任何输出说明网易云音乐的请求依然没有被正确转发…

**Comment by yi-ji** [comment]
请下载该工具最新版，并尝试一下用system python而非IPython？

**Comment by SkyOL5** [comment]
抱歉抱歉！拉错了文件，我已下载最新版本，然后在自动代理关闭的情况下：
Last login: Thu Dec 20 19:45:53 on ttys000
vlan-2661-10-19-244-218:~ skyol$ cd /Users/skyol/Downloads/NeteaseMusicAbroad-master
vlan-2661-10-19-244-218:NeteaseMusicAbroad-master skyol$ /bin/bash -x run_Darwin.sh
++ get_network_service_name
+++ networksetup -listnetworkserviceorder
+++ grep 'Hardware Port'
++ services='(Hardware Port: Wi-Fi, Device: en0)
(Hardware Port: Bluetooth PAN, Device: en6)
(Hardware Port: Thunderbolt Bridge, Device: bridge0)'
+++ echo '(Hardware Port: Wi-Fi, Device: en0)
(Hardware Port: Bluetooth PAN, Device: en6)
(Hardware Port: Thunderbolt Bridge, Device: bridge0)'
++ read line
+++ echo '(Hardware' Port: Wi-Fi, Device: 'en0)'
+++ awk -F '(, )|(: )|[)]' '{print $2}'
++ sname=Wi-Fi
+++ echo '(Hardware' Port: Wi-Fi, Device: 'en0)'
+++ awk -F '(, )|(: )|[)]' '{print $4}'
++ sdev=en0
++ '[' -n en0 ']'
+++ ifconfig en0
++ ifout='en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether dc:a9:04:8c:c0:fe 
	inet6 fe80::103b:36c3:8e8f:8702%en0 prefixlen 64 secured scopeid 0x7 
	inet 10.19.244.218 netmask 0xfffff800 broadcast 10.19.247.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active'
++ echo 'en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether dc:a9:04:8c:c0:fe 
	inet6 fe80::103b:36c3:8e8f:8702%en0 prefixlen 64 secured scopeid 0x7 
	inet 10.19.244.218 netmask 0xfffff800 broadcast 10.19.247.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active'
++ grep 'status: active'
++ rc=0
++ '[' 0 -eq 0 ']'
++ currentservice=Wi-Fi
++ read line
+++ echo '(Hardware' Port: Bluetooth PAN, Device: 'en6)'
+++ awk -F '(, )|(: )|[)]' '{print $2}'
++ sname='Bluetooth PAN'
+++ echo '(Hardware' Port: Bluetooth PAN, Device: 'en6)'
+++ awk -F '(, )|(: )|[)]' '{print $4}'
++ sdev=en6
++ '[' -n en6 ']'
+++ ifconfig en6
++ ifout=
++ echo ''
++ grep 'status: active'
++ rc=1
++ '[' 1 -eq 0 ']'
++ read line
+++ echo '(Hardware' Port: Thunderbolt Bridge, Device: 'bridge0)'
+++ awk -F '(, )|(: )|[)]' '{print $2}'
++ sname='Thunderbolt Bridge'
+++ echo '(Hardware' Port: Thunderbolt Bridge, Device: 'bridge0)'
+++ awk -F '(, )|(: )|[)]' '{print $4}'
++ sdev=bridge0
++ '[' -n bridge0 ']'
+++ ifconfig bridge0
++ ifout='bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether c2:00:80:d0:f7:01 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 10 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 11 priority 0 path cost 0
	member: en3 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 12 priority 0 path cost 0
	member: en4 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 13 priority 0 path cost 0
	Address cache:
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive'
++ echo 'bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether c2:00:80:d0:f7:01 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 10 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 11 priority 0 path cost 0
	member: en3 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 12 priority 0 path cost 0
	member: en4 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 13 priority 0 path cost 0
	Address cache:
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive'
++ grep 'status: active'
++ rc=1
++ '[' 1 -eq 0 ']'
++ read line
++ '[' -n Wi-Fi ']'
++ echo Wi-Fi
+ network_service_name=Wi-Fi
+ print_log 'The change been made can be recovered at: System Preference -> Network -> Advanced -> Proxies -> Automatic Proxy Configuration.'
+ echo ''
+ echo The change been made can be recovered at: System Preference '->' Network '->' Advanced '->' Proxies '->' Automatic Proxy Configuration.
+ networksetup -setautoproxystate Wi-Fi on
++ networksetup -getautoproxyurl Wi-Fi
++ head -1
++ awk -F :// '{print $2}'
+ pac_file=
+ '[' '!' -e ']'
+ grep -q Yes
+ networksetup -getautoproxyurl Wi-Fi
+ print_log 'All set, launching NeteaseMusic App now...'
+ echo ''
+ nohup python NeteaseMusicProxy.py
+ echo All set, launching NeteaseMusic App now...
+ print_log 'Don'\''t worry about me, I will terminate myself a few seconds after you quit NeteaseMusic.'
+ echo ''
+ echo 'Don'\''t' worry about me, I will terminate myself a few seconds after you quit NeteaseMusic.
+ nohup /Applications/NeteaseMusic.app/Contents/MacOS/NeteaseMusic
++ pgrep -f NeteaseMusicProxy
appending output to nohup.out
+ pid='13022
13644'
+ true
+ sleep 60

++ pgrep NeteaseMusic
++ wc -l
++ xargs
+ '[' 1 -eq 1 ']'
+ kill -9 13022 13644
run_Darwin.sh: line 59: kill: (13022) - No such process
+ break


运行完之后，自动代理配置被自动勾选上，但是没有对应的配置文件路径

**Comment by SkyOL5** [comment]
使用系统python3运行结果没有差异：
Last login: Thu Dec 20 19:49:32 on ttys000
vlan-2661-10-19-244-218:~ skyol$ python3 /Users/skyol/Downloads/NeteaseMusicAbroad-master/NeteaseMusicProxy.py
2018-12-20 19:56:32+1100 [-] Log opened.
2018-12-20 19:56:34+1100 [-] NeteaseMusicProxyFactory starting on 32794
2018-12-20 19:56:34+1100 [-] Starting factory <__main__.NeteaseMusicProxyFactory object at 0x10551cc18>
在等待响应【在运行之前，我开启了自动代理配置，并且正确输入了pac文件地址】

**Comment by SkyOL5** [comment]
哇，老哥，成功了！
我把系统改成中文，就能识别了
目测是中文版的时候，地址栏是 下载，英文版的地址栏是Downloads 。。。。

**Comment by yi-ji** [comment]
这也可以.jpg 😂😂
但是英文的时候路径不也是英文么？

**Comment by SkyOL5** [comment]
2333，中文版本下，路径是 file:///Users/skyol/下载/......但我输入的是file:///Users/skyol/Download/...可能是没有识别？不太懂
