### ISSUE TITLE
尝试后不能使用

### ISSUE THREAD

**Issue by Dalanke** [yi-ji/NeteaseMusicAbroad#27]
python NeteaseMusicProxy.py输出如下：
2019-01-08 17:57:50-0500 [-] Log opened.
2019-01-08 17:57:51-0500 [-] Traceback (most recent call last):
2019-01-08 17:57:51-0500 [-]   File "NeteaseMusicProxy.py", line 267, in <module>
2019-01-08 17:57:51-0500 [-]     kill_existed()
2019-01-08 17:57:51-0500 [-]   File "NeteaseMusicProxy.py", line 15, in kill_existed
2019-01-08 17:57:51-0500 [-]     existed = pgrep.communicate()[0].rstrip().split('\n')
2019-01-08 17:57:51-0500 [-] TypeError: a bytes-like object is required, not 'str'
自动代理配置勾选了 但是没有路径 手动添加后也没有效果
Python 3.6.8 :: Anaconda, Inc.|Mac 10.13.1|网易云1.5.10

**Comment by yi-ji** [comment]
小bug，已修复，谢谢提醒！

另外，好几个issue都提到“自动代理配置勾选了但是没有路径”， 所以可以麻烦收集一下debug信息吗？先手动清空路径，然后在terminal执行 `/bin/bash -x run_Darwin.sh` 贴一下输出🙏

**Comment by Dalanke** [comment]
感谢修复，执行/bin/bash -x run_Darwin.sh
输出如下 
================================
++ get_network_service_name
+++ networksetup -listnetworkserviceorder
+++ grep 'Hardware Port'
++ services='(Hardware Port: USB 10/100/1000 LAN, Device: en4)
(Hardware Port: USB 10/100/1000 LAN, Device: en4)
(Hardware Port: Wi-Fi, Device: en0)
(Hardware Port: Bluetooth PAN, Device: en3)
(Hardware Port: Thunderbolt Bridge, Device: bridge0)'
+++ echo '(Hardware Port: USB 10/100/1000 LAN, Device: en4)
(Hardware Port: USB 10/100/1000 LAN, Device: en4)
(Hardware Port: Wi-Fi, Device: en0)
(Hardware Port: Bluetooth PAN, Device: en3)
(Hardware Port: Thunderbolt Bridge, Device: bridge0)'
++ read line
+++ echo '(Hardware' Port: USB 10/100/1000 LAN, Device: 'en4)'
+++ awk -F '(, )|(: )|[)]' '{print $2}'
++ sname='USB 10/100/1000 LAN'
+++ echo '(Hardware' Port: USB 10/100/1000 LAN, Device: 'en4)'
+++ awk -F '(, )|(: )|[)]' '{print $4}'
++ sdev=en4
++ '[' -n en4 ']'
+++ ifconfig en4
++ ifout=
++ echo ''
++ grep 'status: active'
++ rc=1
++ '[' 1 -eq 0 ']'
++ read line
+++ echo '(Hardware' Port: USB 10/100/1000 LAN, Device: 'en4)'
+++ awk -F '(, )|(: )|[)]' '{print $2}'
++ sname='USB 10/100/1000 LAN'
+++ echo '(Hardware' Port: USB 10/100/1000 LAN, Device: 'en4)'
+++ awk -F '(, )|(: )|[)]' '{print $4}'
++ sdev=en4
++ '[' -n en4 ']'
+++ ifconfig en4
++ ifout=
++ echo ''
++ grep 'status: active'
++ rc=1
++ '[' 1 -eq 0 ']'
++ read line
+++ echo '(Hardware' Port: Wi-Fi, Device: 'en0)'
+++ awk -F '(, )|(: )|[)]' '{print $2}'
++ sname=Wi-Fi
+++ echo '(Hardware' Port: Wi-Fi, Device: 'en0)'
+++ awk -F '(, )|(: )|[)]' '{print $4}'
++ sdev=en0
++ '[' -n en0 ']'
+++ ifconfig en0
++ ifout='en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 78:4f:43:9d:d2:d2 
	inet6 fe80::14eb:3ec6:8c76:b0cb%en0 prefixlen 64 secured scopeid 0x6 
	inet 192.168.1.12 netmask 0xffffff00 broadcast 192.168.1.255
	inet6 2601:18d:4600:10d0:1820:6ae2:e76f:5527 prefixlen 64 autoconf secured 
	inet6 2601:18d:4600:10d0:105d:854c:788b:5266 prefixlen 64 autoconf temporary 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active'
++ echo 'en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 78:4f:43:9d:d2:d2 
	inet6 fe80::14eb:3ec6:8c76:b0cb%en0 prefixlen 64 secured scopeid 0x6 
	inet 192.168.1.12 netmask 0xffffff00 broadcast 192.168.1.255
	inet6 2601:18d:4600:10d0:1820:6ae2:e76f:5527 prefixlen 64 autoconf secured 
	inet6 2601:18d:4600:10d0:105d:854c:788b:5266 prefixlen 64 autoconf temporary 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active'
++ grep 'status: active'
++ rc=0
++ '[' 0 -eq 0 ']'
++ currentservice=Wi-Fi
++ read line
+++ echo '(Hardware' Port: Bluetooth PAN, Device: 'en3)'
+++ awk -F '(, )|(: )|[)]' '{print $2}'
++ sname='Bluetooth PAN'
+++ echo '(Hardware' Port: Bluetooth PAN, Device: 'en3)'
+++ awk -F '(, )|(: )|[)]' '{print $4}'
++ sdev=en3
++ '[' -n en3 ']'
+++ ifconfig en3
++ ifout=
++ echo ''
++ grep 'status: active'
++ rc=1
++ '[' 1 -eq 0 ']'
++ read line
+++ echo '(Hardware' Port: Thunderbolt Bridge, Device: 'bridge0)'
+++ awk -F '(, )|(: )|[)]' '{print $2}'
++ sname='Thunderbolt Bridge'
+++ echo '(Hardware' Port: Thunderbolt Bridge, Device: 'bridge0)'
+++ awk -F '(, )|(: )|[)]' '{print $4}'
++ sdev=bridge0
++ '[' -n bridge0 ']'
+++ ifconfig bridge0
++ ifout='bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 9a:00:cd:50:0d:00 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 10 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 9 priority 0 path cost 0
	Address cache:
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive'
++ echo 'bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 9a:00:cd:50:0d:00 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 10 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 9 priority 0 path cost 0
	Address cache:
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive'
++ grep 'status: active'
++ rc=1
++ '[' 1 -eq 0 ']'
++ read line
++ '[' -n Wi-Fi ']'
++ echo Wi-Fi
+ network_service_name=Wi-Fi
+ print_log 'The change been made can be recovered at: System Preference -> Network -> Advanced -> Proxies -> Automatic Proxy Configuration.'
+ echo ''
+ echo The change been made can be recovered at: System Preference '->' Network '->' Advanced '->' Proxies '->' Automatic Proxy Configuration.
+ networksetup -setautoproxystate Wi-Fi on
++ networksetup -getautoproxyurl Wi-Fi
++ head -1
++ awk -F :// '{print $2}'
+ pac_file=
+ '[' '!' -e ']'
+ networksetup -getautoproxyurl Wi-Fi
+ grep -q Yes
+ print_log 'All set, launching NeteaseMusic App now...'
+ echo ''
+ echo All set, launching NeteaseMusic App now...
+ nohup python NeteaseMusicProxy.py
+ print_log 'Don'\''t worry about me, I will terminate myself a few seconds after you quit NeteaseMusic.'
+ echo ''
+ echo 'Don'\''t' worry about me, I will terminate myself a few seconds after you quit NeteaseMusic.
+ nohup /Applications/NeteaseMusic.app/Contents/MacOS/NeteaseMusic
++ pgrep -f NeteaseMusicProxy
appending output to nohup.out
+ pid=5115
+ true
+ sleep 60
++ pgrep NeteaseMusic
++ wc -l
++ xargs
+ '[' 2 -eq 1 ']'
+ true
+ sleep 60
=======================
此外 直接启动helper并没有效果 要手动python NeteaseMusicProxy.py 才能解除限制

**Comment by yi-ji** [comment]
多谢！问题已修复！现在应该直接启动helper即可

**Comment by Dalanke** [comment]
测试可以使用！非常感谢
