### ISSUE TITLE
pip的时候遇到error: command 'cc' failed with exit status 1解决办法

### ISSUE THREAD

**Issue by lijunray** [yi-ji/NeteaseMusicAbroad#28]
先感谢作者！Saved my life！
安装python依赖包的时候遇到了这个error，已自行解决，贴在这里给遇到这个问题的小伙伴作为参考：https://stackoverflow.com/questions/22697440/cc-failed-with-exit-status-1-error-when-install-python-library

我是通过安装`xcode-select`解决的：
```
xcode-select --install
```

**Comment by yi-ji** [comment]
感谢分享！
