### ISSUE TITLE
Arch下运行网易云音乐提示网络连接失败

### ISSUE THREAD

**Issue by chzenze** [yi-ji/NeteaseMusicAbroad#30]
手动运行python NeteaseMusicProxy.py 发现会把自己kill掉
2019-01-26 17:04:40-0600 [-] Log opened.
[1]    2204 killed     python NeteaseMusicProxy.py
注释了kill_existed()以后就正常了

**Comment by ntulsy** [comment]
我也遇到了同样的问题。
ubuntu 18.04. git pull了最新版本也是一样的。

**Comment by chzenze** [comment]
注释了kill_existed()以后就正常了

**Comment by yi-ji** [comment]
抱歉，忘记测试python3了，是byte string的问题，已修复

**Comment by ntulsy** [comment]
谢谢@yi-ji python3已测试 没有问题了
