### ISSUE TITLE
网易云会员好像是必要的？

### ISSUE THREAD

**Issue by lucia520** [yi-ji/NeteaseMusicAbroad#32]
本来是没有网易云会员的
按照上面的都做了
但是打开后刷了三次后只有短暂的两三次名称变黑
然后就又回到灰色
检查了好几次发现应该没有什么不对的
于是充了一个月会员
之后就可行了

**Comment by lucia520** [comment]
？？？我今天早上发现，我不运行代码，直接打开网易云，也能听？
所以不需要代码
充个会员就可以？？？？

**Comment by yi-ji** [comment]
会员是必要的，这个工具只帮你解除锁区的限制。锁区就是只能在大陆地区播放（如果不是会员在哪都无法播放）。
网易云音乐有一定的cache机制，你可以这样用一段时间，之后应该又会变灰。
