### ISSUE TITLE
网络设置显示加载了pac 但是mac版显示网络连接失败

### ISSUE THREAD

**Issue by Ada-Wu** [yi-ji/NeteaseMusicAbroad#4]
mac版网易云直接显示网络连接失败，请问可能是什么原因呢？python脚本可以运行成功

**Comment by yi-ji** [comment]
因为这个工具有可能会影响到一部分https请求，所以网易云音乐的专辑封面以及部分页面的加载可能受到影响。但歌单是可以正常点开播放的。如果不行，麻烦截个图看看，并且直接运行python脚本把输出贴上来。
注：网易云音乐升到1.5.9似乎这个问题会消失。
