### ISSUE TITLE
Can't run past line 137 for NeteaseMusicProxy.py

### ISSUE THREAD

**Issue by pandatastic** [yi-ji/NeteaseMusicAbroad#43]
It will run for about 30 minutes, but when I interrupt it, it says finished exit code 137.

Thank you!

**Comment by pandatastic** [comment]
2019-08-21 12:26:14-0400 [-] Log opened.
2019-08-21 12:26:16-0400 [-] NeteaseMusicProxyFactory starting on 32794
2019-08-21 12:26:16-0400 [-] Starting factory <__main__.NeteaseMusicProxyFactory object at 0x11154a390>
Killed: 9

**Comment by yi-ji** [comment]
Please update to the latest commit if you are not by any chance;
please check if port 32794 has already been taken on your machine. You can change it to another number in the code and see if it works.
If the problem still exists, please read the FAQ and then report necessary info.

**Comment by yi-ji** [comment]
Closing this issue due to long time radio silence
