### ISSUE TITLE
python setup.py egg_info" failed with error code 1 in blahblah

### ISSUE THREAD

**Issue by NathanZhengNaixian** [yi-ji/NeteaseMusicAbroad#45]
Last login: Sun Mar 15 17:41:26 on ttys001
$ pip install twisted requests pyquery --user

Collecting twisted
  Using cached https://files.pythonhosted.org/packages/0b/95/5fff90cd4093c79759d736e5f7c921c8eb7e5057a70d753cdb4e8e5895d7/Twisted-19.10.0.tar.bz2
    Complete output from command python setup.py egg_info:
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'tests'
    warning: no previously-included files found matching 'examplesetup.py'
    no previously-included directories found matching 'src/exampleproj'
    no previously-included directories found matching 'src/incremental/newsfragments'

    Installed /private/var/folders/jk/5rrhdq9n1dvf0s9ft5k74r1r0000gq/T/pip-install-jxGccI/twisted/.eggs/incremental-17.5.0-py2.7.egg
    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    error in Twisted setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

    ----------------------------------------
**_Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jk/5rrhdq9n1dvf0s9ft5k74r1r0000gq/T/pip-install-jxGccI/twisted/_**
You are using pip version 18.0, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

报错了我看

**Comment by NathanZhengNaixian** [comment]
是因为我 pip 的原因吗

**Comment by yi-ji** [comment]
请尝试 `pip install --user --upgrade setuptools`

**Comment by NathanZhengNaixian** [comment]
谢谢回复，可我pip 还是 18.0， 命令输入了之后也是

**Comment by yi-ji** [comment]
`pip install --user --upgrade setuptools` 这个是更新了一些setuptools, 现在再尝试重新执行`pip install twisted requests pyquery --user`?
