### ISSUE TITLE
失效

### ISSUE THREAD

**Issue by Xiangwei-Peng** [yi-ji/NeteaseMusicAbroad#6]
您好，我按照步骤错过没有成功。

网易云 版本 1.5.9
macOS 版本 10.12.6

但是我的python 通过Anaconda3 安装了Python 3.6.5，现在通过terminal打开Python都默认的是这个版本。系统版本没有删除。 请问我需要卸载了 Anaconda3才可以用么？

**Comment by Xiangwei-Peng** [comment]
网易云 版本 1.5.9
macOS 版本 10.12.6
python 版本 3.6.5

哦哦，可能是Python版本的问题~~ 打扰打扰

**Comment by yi-ji** [comment]
你好，是python版本的问题，不过现在已经支持python3了， 请重新下载最新的NeteaseMusicAbroad。
还有什么问题的话请继续在这里报告 :)
